apiVersion: v1
data:
  aidb-api-key: ZGNiNmIzNDM1NDY3Y2ZiNDdjZDM4NWEwMzMxMWIyZDJkMDgxNDk2Y2ZlNDc1MmU5NTZlMjQ2NDljZmI3ZGFjNg==
kind: Secret
metadata:
  labels:
    io.kompose.service: aidb-api-key
  name: aidb-api-key
type: Opaque
