apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.37.0 (HEAD)
    nixos.quick-deploy.ai-stack: "true"
    nixos.quick-deploy.service: aidb
  labels:
    io.kompose.service: aidb
  name: aidb
spec:
  ports:
    - name: "8091"
      port: 8091
      targetPort: 8091
  selector:
    io.kompose.service: aidb
