apiVersion: v1
data:
  aider-wrapper-api-key: NjlhNmE2MjQ1OTUwNWFiNjE5N2YwNGFjOTdiODU4ZWVlMWMwNjg5OTg2ZDg4YjVjNzFkOTE3NzA4MDA4YjViZQ==
kind: Secret
metadata:
  labels:
    io.kompose.service: aider-wrapper-api-key
  name: aider-wrapper-api-key
type: Opaque
