apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.37.0 (HEAD)
    nixos.quick-deploy.ai-stack: "true"
    nixos.quick-deploy.service: aider
  labels:
    io.kompose.service: aider
  name: aider
spec:
  ports:
    - name: "8093"
      port: 8093
      targetPort: 8093
  selector:
    io.kompose.service: aider
