apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.37.0 (HEAD)
    nixos.quick-deploy.agent-backend: aider
    nixos.quick-deploy.ai-stack: "true"
    nixos.quick-deploy.service: aider-wrapper
  labels:
    io.kompose.service: aider-wrapper
  name: aider-wrapper
spec:
  ports:
    - name: "8099"
      port: 8099
      targetPort: 8099
  selector:
    io.kompose.service: aider-wrapper
