apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /nix/store/x4z1n3wj7pscmifwnh2yvczxqg6vay39-kompose-1.37.0/bin/kompose convert -f ai-stack/compose/docker-compose.yml -o ai-stack/kubernetes/kompose
    kompose.version: 1.37.0 (HEAD)
    nixos.quick-deploy.ai-stack: "true"
    nixos.quick-deploy.service: container-engine-mcp
  labels:
    io.kompose.service: container-engine
  name: container-engine
spec:
  ports:
    - name: "8095"
      port: 8095
      targetPort: 8095
  selector:
    io.kompose.service: container-engine
