apiVersion: v1
data:
  container-engine-api-key: ZThiY2Y0Y2E4N2ZkMzA5ZjA4ZjJjYmI0NTJkMDYwYzM4ZDMzNDNhZDdhNzQ3MzE2ZGQ4ZjA5MmMyMTM2NTE1OA==
kind: Secret
metadata:
  labels:
    io.kompose.service: container-engine-api-key
  name: container-engine-api-key
type: Opaque
