apiVersion: v1
data:
  embeddings_api_key: Mjg5MjBiMDQzYzZkODA3NGNiYjk0MDA5NDg5M2EwMmU1NGNmMDNjMzhiMzUyMjQzNWE0OWRjN2M5MmEzNjA4Ng==
kind: Secret
metadata:
  labels:
    io.kompose.service: embeddings-api-key
  name: embeddings-api-key
type: Opaque
