apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /nix/store/x4z1n3wj7pscmifwnh2yvczxqg6vay39-kompose-1.37.0/bin/kompose convert -f ai-stack/compose/docker-compose.yml -o ai-stack/kubernetes/kompose
    kompose.version: 1.37.0 (HEAD)
    nixos.quick-deploy.ai-stack: "true"
    nixos.quick-deploy.service: grafana
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /nix/store/x4z1n3wj7pscmifwnh2yvczxqg6vay39-kompose-1.37.0/bin/kompose convert -f ai-stack/compose/docker-compose.yml -o ai-stack/kubernetes/kompose
        kompose.version: 1.37.0 (HEAD)
        nixos.quick-deploy.ai-stack: "true"
        nixos.quick-deploy.service: grafana
      labels:
        io.kompose.service: grafana
    spec:
      containers:
        - env:
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "false"
            - name: GF_SECURITY_ADMIN_PASSWORD__FILE
              value: /run/secrets/grafana-admin-password
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
          envFrom:
            - configMapRef:
                name: env
          image: grafana/grafana:11.2.0
          name: local-ai-grafana
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /run/secrets/grafana-admin-password
              name: grafana-admin-password
              subPath: grafana-admin-password
      restartPolicy: Always
      volumes:
        - name: grafana-admin-password
          secret:
            defaultMode: 292
            items:
              - key: grafana-admin-password
                path: grafana-admin-password
            secretName: grafana-admin-password
