apiVersion: v1
data:
  grafana-admin-password: VUE2RlV2V2JFc2FBUFBmRWMySEpUTE5GUUM1Y2t6d1c=
kind: Secret
metadata:
  labels:
    io.kompose.service: grafana-admin-password
  name: grafana-admin-password
type: Opaque
