apiVersion: v1
data:
  hybrid-coordinator-api-key: ZmNhYmYyZTYwM2U0NTg5ZDJiNDdlZGQyYWNjNWU2ODcyZDIzNGIxY2NkMTc5MzQxYzg3ZjU1YmY0MjAxNTkzOA==
kind: Secret
metadata:
  labels:
    io.kompose.service: hybrid-coordinator-api-key
  name: hybrid-coordinator-api-key
type: Opaque
