apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /nix/store/x4z1n3wj7pscmifwnh2yvczxqg6vay39-kompose-1.37.0/bin/kompose convert -f ai-stack/compose/docker-compose.yml -o ai-stack/kubernetes/kompose
    kompose.version: 1.37.0 (HEAD)
    nixos.quick-deploy.ai-stack: "true"
    nixos.quick-deploy.service: mindsdb
  labels:
    io.kompose.service: mindsdb
  name: mindsdb
spec:
  ports:
    - name: "47334"
      port: 47334
      targetPort: 47334
  selector:
    io.kompose.service: mindsdb
