apiVersion: v1
data:
  .gitkeep: ""
  localhost.crt: |
    -----BEGIN CERTIFICATE-----
    MIIF+jCCA+KgAwIBAgIUbeymXm3UmIK0aEm7+jgq0NllmBwwDQYJKoZIhvcNAQEL
    BQAwYDELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBUxvY2FsMRQwEgYDVQQHDAtEZXZl
    bG9wbWVudDEXMBUGA1UECgwOTml4T1MgQUkgU3RhY2sxEjAQBgNVBAMMCWxvY2Fs
    aG9zdDAeFw0yNjAxMDgxODMyMThaFw0yNzAxMDgxODMyMThaMGAxCzAJBgNVBAYT
    AlVTMQ4wDAYDVQQIDAVMb2NhbDEUMBIGA1UEBwwLRGV2ZWxvcG1lbnQxFzAVBgNV
    BAoMDk5peE9TIEFJIFN0YWNrMRIwEAYDVQQDDAlsb2NhbGhvc3QwggIiMA0GCSqG
    SIb3DQEBAQUAA4ICDwAwggIKAoICAQCz4EyOiCmkANclXgackULJJO7CZz1K8f91
    dXxTcxr617h1lHCMKWlfFeI2I2c1GRj03SlyLZajFUdWwlV8uGZPWpTgik7AYqwb
    W94cE5OkdX15ouctD0I6O13bDoMa2S7kndN1UVWi4qZT2PXB0VI6Xihli+CaFKlH
    hNMQBztawMK5z2A4KAyRr4f2Yjdl5ZA+GqcTaUz2C794vXHahNf1TOV2Nh/FT0B/
    l/O056VLkUYaAdOOqci2B1anO9n1EKzisu4i7VJR8Cdpy1kW/Lc9A4Px18N+p6VS
    xbnpe0NAxn3sFQ/LulRO9awwuplUZ/0jy98e3UZPsSjiUOK8CYxoKQJox2xsBsgr
    ZSeBSIrl29J1SBmcxNdePmgC5HSmHhFBArTAHvOuhsymp9O/SelgnONEX3Z73JJt
    AEX5GgpI/k9T66GeXxqgWowCd/HbJyY2zyLvfSXyMQmisOcwNuFlhD05JJRLozjK
    6KtZIi59UPDDg3KZcwL6nOeBTeKijSbW+xkh0HaYrnoOzfybag4GeNchpnPSOl5a
    GhnWUE0/h5IPMUWitFVl1Y6ZOhOf/m1thNHOswRTwlIm14u4c7dTH8MiD047hUrL
    ebz14gHctbAykv8n9/eZDn/An/p9L2prWyTo6Qnwm3x8f80CUyXF/yUXlvXcVlDO
    MWjtaVKweQIDAQABo4GrMIGoMB0GA1UdDgQWBBQDVkdNswSvzjiUT4alchMTTjMK
    ITAfBgNVHSMEGDAWgBQDVkdNswSvzjiUT4alchMTTjMKITA5BgNVHREEMjAwggls
    b2NhbGhvc3SCCyoubG9jYWxob3N0hwR/AAABhxAAAAAAAAAAAAAAAAAAAAABMAkG
    A1UdEwQCMAAwCwYDVR0PBAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMA0GCSqG
    SIb3DQEBCwUAA4ICAQAjAwnl0/H3fdEufrrFZ6S8mSjzrIyKPDbykCZFoDtmxv9J
    sZFuGaBwbmdplkHD1kjW2mYxJkEwAzv3XQ2/JIoh/3EVwE55OY/8WFgqUxOEzYhA
    77UdbEbr7lPBNJgGE/tlgNVtlbnn3suArlh46jtk6WoOkDiUXHepqD7n2Ab3hRdl
    ciB/KnbMzFPxbiAsD1zoZn7I492s+wIVbIKITHjMBO+zs6+5DSZWglN4LYUEKggA
    cj48yMOYQEeu88GHaCYlwkdIr9nobJUFMbT2cW1YUgjlrL06UzOc68yYwePoboLl
    F6LzeLZrI1fr6yTc/UmGNhZ03J+8QI2a7f2+qyMoz43dS2SEDFDcT7Lk2BX6w4PN
    spxnKBV5wtATIJAvQTypfYhFOYuwi8a2qVQGMIMye0q83a0tFplp6d0pvJYhsNub
    nAO+vnFMv+39anAf2DmKBeGMyDzMmpqoYvkkxU4WpGj+Av+EkEsiY9VIPms08uWq
    Bj9VXnlRg5PJlWm00OV+4c7PB9E8HE9KJRa8YdxMnc9fldZmLlTinBSqiUJAKGX1
    IeVachhbk5NaiQ8ZgtV0CzczfO15m7WbGsXKrDAYlwh+q+B/RD0EovFJR6Pv0K1G
    ElAA6erSdTml28duUWbbQtiYf9XFWneDMG8M9fKQXZWx5ZXDkV/TjqcVImd/3g==
    -----END CERTIFICATE-----
  localhost.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQCz4EyOiCmkANcl
    XgackULJJO7CZz1K8f91dXxTcxr617h1lHCMKWlfFeI2I2c1GRj03SlyLZajFUdW
    wlV8uGZPWpTgik7AYqwbW94cE5OkdX15ouctD0I6O13bDoMa2S7kndN1UVWi4qZT
    2PXB0VI6Xihli+CaFKlHhNMQBztawMK5z2A4KAyRr4f2Yjdl5ZA+GqcTaUz2C794
    vXHahNf1TOV2Nh/FT0B/l/O056VLkUYaAdOOqci2B1anO9n1EKzisu4i7VJR8Cdp
    y1kW/Lc9A4Px18N+p6VSxbnpe0NAxn3sFQ/LulRO9awwuplUZ/0jy98e3UZPsSji
    UOK8CYxoKQJox2xsBsgrZSeBSIrl29J1SBmcxNdePmgC5HSmHhFBArTAHvOuhsym
    p9O/SelgnONEX3Z73JJtAEX5GgpI/k9T66GeXxqgWowCd/HbJyY2zyLvfSXyMQmi
    sOcwNuFlhD05JJRLozjK6KtZIi59UPDDg3KZcwL6nOeBTeKijSbW+xkh0HaYrnoO
    zfybag4GeNchpnPSOl5aGhnWUE0/h5IPMUWitFVl1Y6ZOhOf/m1thNHOswRTwlIm
    14u4c7dTH8MiD047hUrLebz14gHctbAykv8n9/eZDn/An/p9L2prWyTo6Qnwm3x8
    f80CUyXF/yUXlvXcVlDOMWjtaVKweQIDAQABAoICAEfc+dkL7071gv8L1KpiooMH
    /VevtV4m1r/Po08XspS68JgRKPHmbZGuhYTJmictkrnpTfCu4/rdunWgCFVeuolD
    kC0xNItKIKaBing/HgJbajjZa3CmIvhu1W16G8jzMffmUiAR0ZvU30yqZmz7utVU
    3uDLBH2qeYL4PvatXPpB/soLXs6wuWzO6wv1a1qLX5hgP5XSwQuf3+xWC5GY90qq
    YRZcQ08p/YO8aoJA9dn9/TrQtfvOO0D2J5mCoO52rguYHunXVMcloilzM3Gqn26B
    5AoQAKuuQK+UDVWJiHHtm0thksD6/UnafuOs+SsurITLo6WKE9gs2D+qvxsO2Yfq
    LC1ge/zaJjGscXJ9nH6ihMvQNmmOawtZzNBWmFAaK49ep54knUFWSmZEXqbkRDy4
    Ejeiaum/+68gZEtZrnbLHoeGXsJuy4k+BVx/+jrP+PkChMx8bCq+JDlpviqrra9w
    j7azMz0gVOG0s9zqdg2bPicMaZieAMGIon3OsLQIP7ML9mlWuARTr3Lwb8S8KHX7
    EF9owoTDGn7nfVy9mA1z4wRo5ebIFEktF182qX1kCYQtilI/BloUMG254JCN4dX/
    t4fJ5NQ24qc9LhBJnc6Oe4DgbvtkKXEJ9SbHkZCoOCoeVySK0ShWUZZFt2e3+M7u
    HQChuClx6qd21Ds0z+ItAoIBAQD6hXCSyaZhovKTZct+UrKVoBNMRgt314zQHwWC
    J8BwFbZJ8O6FcA+tgmjbJcyu5iK14lxkrhehvCE/HGuHwuqk8t4N/ZTzNZwV09tq
    QfCayuPcyhsvOve4kiqJcG0mh3hRJUzfme79UV+KzBgx5RfpiRvK47M84sLB/HJO
    RldsL/8xte93R51/tuUN26uStat/12xR7190m8tL1mZ81GArwJOTah8ZPmGiKFTh
    iYduQc2xaguDfar4xWoCIxGO35o5Tm4z7QFSOzW3a71u+rIpYr6OUi91nE6oAMOi
    jQHLfCLSNMZ98yzgItds8oxVr1LkkkefXaEb8gelX0QY+pyXAoIBAQC3z1kXsPwp
    hTKxSPNs+STSu2YrFn7mx/jiRaUDLhn+UQUVP7WYWMRUayf/kkF15YnUg+Vh5iRv
    CLdw/mr9PCE3KCo4Mhf5eIHm2dwWWj/N/n0GBVcw//p/NB4db7zgV1CadTw6tl37
    Yxyzyi1t/oVGcCYY5dRLIjohI4c1hIwKfR85I1GB6ZTJm7SW/Q1omGfEHBta+JuW
    OFXm2c9cYF66htl9WsTtqyt+AUYdfzuZmL8/5kiEC5TJkHkw5vsNiDlR89eUReEK
    75yk2G09hAVmsETr5Dlj5F3ufLZy/ywAIB/5POrBnwyjA99Lcp8PnTK7B67xKcZy
    XTKcd3Xk9+1vAoIBADWMABvf7ihAZAkNYQmHM5S3umg7MIhVEkwJ1WuUg5Vxjp0P
    Wmw7H56+mRr+YVmg5xppX8ZFT9fKFnEe6f0CtJS9NKlY4lV5x/sCZYu4vGzZoQq4
    SEc4G2rgEyd9WFc77YOqrVu9009h7UIFjcZcaVgJbl9XfCAvd+FuzB/e+SCuwaUm
    diDQteFuflcP9QROwHF64jRBLe4GvtVe5lkYK9YuO1zu+eazZrr6U+pBMyll90lM
    mVlpqvmxeI8sX7xiHtzQ3s1Kg1XIQhsKdFscSqh96q0Q9AP3fPh78VT1PsT3q5my
    nhqdt6HQ0KsAzO4jo1wnyBdQM/d9LBU036FXL9ECggEACioFGzJGP2WGMBeAnn4I
    cz65n5hW3BwivyBqx4o9FbsVNN+ZAxulf6WNSKylwgc3X/ELNiarzRgGTNFEyUwR
    6iLmcsUSXlEznbheWz4SWSnBcBvLfoIpL++J2sbbAuzRIDlrYzPCbqxEYgzEBlkU
    tZhuAuJyotT5settBqCVvd69Y0N4tl5cQ+nASrkjjK0gz89eE+G7eMsUtPdGaC1M
    D7R1QmFKknnspcMcRXVLrmqr6LSrPeIGED9U9EdRiqYFxWpeeWyDzT8CwnrVT5mF
    UvBcX073fXabWxy6WhGSNU+RdQ7RTHOnFzyXlGx6LzraG02JdvyAZMKSkeRpOIgd
    MQKCAQBXRIgknb2fqwawV5tRyUrmdVGNTY2gCmRkdOQ4wbS9EZ0eZXzRBF9zIIXD
    ZnMNuiVu1q5AftE2Alo4NtDxZzY7qT0Hkh7El8CQLFTACPi4Aud0z0CeyJftFtZa
    8GIQPl03L9HVxyAfTYnd4pKICNqHrZsbH7hCS7PHnLjZQZjSfzcDpPo2hMHomh9/
    ZmA+4Zrmc57BwO81ZSZKzta1OXlkWiOvIGLUTg7LGCvTZwW8EtOsFg4XKu/ikdhX
    y9GhTE2OI3nTGIBoDShgw/TTZhK/iF9M+PnB93bohjyxp/DM6yOLLLvfObpVMg4A
    3DxEfnZcPOdUiZ8S9vs6hKFfrp7l
    -----END PRIVATE KEY-----
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: nginx
  name: nginx-cm1
