apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.37.0 (HEAD)
    nixos.quick-deploy.ai-stack: "true"
    nixos.quick-deploy.service: nginx
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
    - name: "8088"
      port: 8088
      targetPort: 80
    - name: "8443"
      port: 8443
      targetPort: 443
  selector:
    io.kompose.service: nginx
