apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.37.0 (HEAD)
    nixos.quick-deploy.ai-stack: "true"
    nixos.quick-deploy.service: nixos-docs
  labels:
    io.kompose.service: nixos-docs
  name: nixos-docs
spec:
  ports:
    - name: http
      port: 8094
      targetPort: 8094
    - name: metrics
      port: 8094
      targetPort: 8094
  selector:
    io.kompose.service: nixos-docs
