apiVersion: v1
data:
  nixos-docs-api-key: ZWU1NDYzNDIzOTkwMDRhOGUwOWQ4Y2FhMzI0MGU0ZTMzZTZjNGFjY2NjOWViOGRkNzUyNDg5ZTk0OTRlZWM0Yg==
kind: Secret
metadata:
  labels:
    io.kompose.service: nixos-docs-api-key
  name: nixos-docs-api-key
type: Opaque
