apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /nix/store/x4z1n3wj7pscmifwnh2yvczxqg6vay39-kompose-1.37.0/bin/kompose convert -f ai-stack/compose/docker-compose.yml -o ai-stack/kubernetes/kompose
    kompose.version: 1.37.0 (HEAD)
    nixos.quick-deploy.ai-stack: "true"
    nixos.quick-deploy.service: open-webui
  labels:
    io.kompose.service: open-webui
  name: open-webui
spec:
  replicas: 0
  selector:
    matchLabels:
      io.kompose.service: open-webui
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /nix/store/x4z1n3wj7pscmifwnh2yvczxqg6vay39-kompose-1.37.0/bin/kompose convert -f ai-stack/compose/docker-compose.yml -o ai-stack/kubernetes/kompose
        kompose.version: 1.37.0 (HEAD)
        nixos.quick-deploy.ai-stack: "true"
        nixos.quick-deploy.service: open-webui
      labels:
        io.kompose.service: open-webui
    spec:
      containers:
        - env:
            - name: ENABLE_OLLAMA_API
              value: "false"
            - name: ENABLE_RAG_WEB_SEARCH
              value: "true"
            - name: OPENAI_API_BASE_URL
              value: http://llama-cpp:8080/v1
            - name: OPENAI_API_KEY
              value: llama-cpp
            - name: PORT
              value: "3001"
            - name: WEBUI_AUTH
              value: "false"
          image: ghcr.io/open-webui/open-webui@sha256:18c1475e636245e2f439b59b4a2b38e1965c881856092d21e5efc38da7e1dac3
          livenessProbe:
            exec:
              command:
                - python
                - -c
                - import urllib.request; r=urllib.request.urlopen('http://localhost:3001', timeout=5); r.read(); import sys; sys.exit(0)
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
          name: local-ai-open-webui
          ports:
            - containerPort: 3001
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: "2147483648"
            requests:
              cpu: 250m
              memory: "536870912"
      restartPolicy: Always
