apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /nix/store/x4z1n3wj7pscmifwnh2yvczxqg6vay39-kompose-1.37.0/bin/kompose convert -f ai-stack/compose/docker-compose.yml -o ai-stack/kubernetes/kompose
    kompose.version: 1.37.0 (HEAD)
    nixos.quick-deploy.ai-stack: "true"
    nixos.quick-deploy.service: postgres
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /nix/store/x4z1n3wj7pscmifwnh2yvczxqg6vay39-kompose-1.37.0/bin/kompose convert -f ai-stack/compose/docker-compose.yml -o ai-stack/kubernetes/kompose
        kompose.version: 1.37.0 (HEAD)
        nixos.quick-deploy.ai-stack: "true"
        nixos.quick-deploy.service: postgres
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              value: mcp
            - name: POSTGRES_PASSWORD_FILE
              value: /run/secrets/postgres-password
            - name: POSTGRES_USER
              value: mcp
          envFrom:
            - configMapRef:
                name: env
          image: pgvector/pgvector:0.8.1-pg18
          livenessProbe:
            exec:
              command:
                - pg_isready -U mcp
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: local-ai-postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: "2147483648"
            requests:
              cpu: 500m
              memory: "268435456"
          volumeMounts:
            - mountPath: /run/secrets/postgres-password
              name: postgres-password
              subPath: postgres-password
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
            - mountPath: /docker-entrypoint-initdb.d/01-init-schema.sql
              name: postgres-cm1
              subPath: 01-init-schema.sql
      restartPolicy: Always
      volumes:
        - name: postgres-password
          secret:
            defaultMode: 292
            items:
              - key: postgres-password
                path: postgres-password
            secretName: postgres-password
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
        - configMap:
            items:
              - key: init-schema.sql
                path: 01-init-schema.sql
            name: postgres-cm1
          name: postgres-cm1
