apiVersion: v1
data:
  postgres-password: a0Rkc1RSZlRYdHVhRW9Bc1F5WW9TZ2YwaXZGeXBlS3Y=
kind: Secret
metadata:
  labels:
    io.kompose.service: postgres-password
  name: postgres-password
type: Opaque
