apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /nix/store/x4z1n3wj7pscmifwnh2yvczxqg6vay39-kompose-1.37.0/bin/kompose convert -f ai-stack/compose/docker-compose.yml -o ai-stack/kubernetes/kompose
    kompose.version: 1.37.0 (HEAD)
    nixos.quick-deploy.ai-stack: "true"
    nixos.quick-deploy.service: qdrant
  labels:
    io.kompose.service: qdrant
  name: qdrant
spec:
  ports:
    - name: "6333"
      port: 6333
      targetPort: 6333
    - name: "6334"
      port: 6334
      targetPort: 6334
  selector:
    io.kompose.service: qdrant
