apiVersion: v1
data:
  ralph-wiggum-api-key: MTg0ZDllOTJjYzhmNmQzMWJlOTc0NjA2Yzk5MmZkMGZlOTJlNmI3MmQ2Zjg0NGE0YzBiNmQ1YWUxMGU4NTMwYQ==
kind: Secret
metadata:
  labels:
    io.kompose.service: ralph-wiggum-api-key
  name: ralph-wiggum-api-key
type: Opaque
