apiVersion: v1
data:
  stack-api-key: YTVlMzA3MzI1NjEzNDRhYzcyZTVhOWI4Njc3MDg5MDU5ZWQ3MmIyY2ZlMGEyMTBiZWY3MjZjMTdiMzk1NDljMg==
kind: Secret
metadata:
  labels:
    io.kompose.service: stack-api-key
  name: stack-api-key
type: Opaque
