apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - backups/namespace.yaml
  - kompose
  - backup-cronjobs.yaml
  - logging/namespace.yaml
  - logging/loki.yaml
  - logging/promtail.yaml
  - network-policies/ai-stack-allow-internal.yaml
